[package]
name = "svm"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["VisualDevelopment"]
license-file = "LICENSE"

[profile.release]
lto = true

[dependencies]
modular-bitfield = "0.11.2"
amd64 = { path = "../AMD64" }
